/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author elian
 */
public class DConfiguracion4 extends javax.swing.JFrame {

    /**
     * Creates new form Configuracion
     */
    public DConfiguracion4() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        setResizable(false);
        getContentPane().setBackground(new Color(57,143,136));
        setIconImage(getIconImage());
    }
    
    @Override
    public final Image getIconImage(){
        
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/icon.png"));
        return retValue;        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonAtras = new javax.swing.JButton();
        botonModificarDatos = new javax.swing.JButton();
        botonBorrarCuenta = new javax.swing.JButton();
        botonModificarContra = new javax.swing.JButton();
        botonID = new javax.swing.JButton();
        panel3 = new java.awt.Panel();
        botonIdentificacionPlanta = new javax.swing.JButton();
        botonCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(57, 143, 136));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Configuracion");

        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonAtras.png"))); // NOI18N
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        botonModificarDatos.setBackground(new java.awt.Color(57, 143, 136));
        botonModificarDatos.setText("Modificar datos de cuenta");
        botonModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarDatosActionPerformed(evt);
            }
        });

        botonBorrarCuenta.setBackground(new java.awt.Color(57, 143, 136));
        botonBorrarCuenta.setText("Borrar cuenta");
        botonBorrarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarCuentaActionPerformed(evt);
            }
        });

        botonModificarContra.setBackground(new java.awt.Color(57, 143, 136));
        botonModificarContra.setText("Modificar contraseña");
        botonModificarContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarContraActionPerformed(evt);
            }
        });

        botonID.setBackground(new java.awt.Color(57, 143, 136));
        botonID.setText("Numero de identificacion de cuenta");
        botonID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIDActionPerformed(evt);
            }
        });

        panel3.setBackground(new java.awt.Color(0, 0, 0));
        panel3.setPreferredSize(new java.awt.Dimension(50, 2));

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        botonIdentificacionPlanta.setBackground(new java.awt.Color(57, 143, 136));
        botonIdentificacionPlanta.setText("Numero de identificaccion de planta");
        botonIdentificacionPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIdentificacionPlantaActionPerformed(evt);
            }
        });

        botonCerrar.setBackground(new java.awt.Color(57, 143, 136));
        botonCerrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonCerrar.setForeground(new java.awt.Color(204, 0, 51));
        botonCerrar.setText("Cerrar Sesion");
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCerrar)
                    .addComponent(botonIdentificacionPlanta)
                    .addComponent(botonModificarContra)
                    .addComponent(botonID)
                    .addComponent(botonModificarDatos)
                    .addComponent(botonBorrarCuenta))
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addComponent(botonModificarDatos)
                .addGap(18, 18, 18)
                .addComponent(botonID)
                .addGap(18, 18, 18)
                .addComponent(botonIdentificacionPlanta)
                .addGap(18, 18, 18)
                .addComponent(botonModificarContra)
                .addGap(18, 18, 18)
                .addComponent(botonBorrarCuenta)
                .addGap(18, 18, 18)
                .addComponent(botonCerrar)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(354, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        
        CPrincipal3 principal = new CPrincipal3();
        principal.setVisible(true);
        principal.setResizable(false);
        principal.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarDatosActionPerformed
        
         EModificacionDatos5 modificacion = new EModificacionDatos5();
         modificacion.setVisible(true);
         modificacion.setResizable(false);
         modificacion.setLocationRelativeTo(null);
         this.dispose();
        
    }//GEN-LAST:event_botonModificarDatosActionPerformed

    private void botonBorrarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarCuentaActionPerformed
        
        HEliminacionCuenta8 confirmacion2 = new HEliminacionCuenta8();
        confirmacion2.setVisible(true);
        setLocationRelativeTo(null);
        setResizable(false);
        this.dispose();
        
    }//GEN-LAST:event_botonBorrarCuentaActionPerformed

    private void botonModificarContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarContraActionPerformed
        
        GConfirmacionContraseña7 confirmacion = new GConfirmacionContraseña7();
        confirmacion.setVisible(true);
        confirmacion.setResizable(false);
        confirmacion.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_botonModificarContraActionPerformed

    private void botonIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIDActionPerformed
        
        FIdentificacionID6 confirmacion = new FIdentificacionID6();
        confirmacion.setVisible(true);
        confirmacion.setResizable(false);
        confirmacion.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_botonIDActionPerformed

    private void botonIdentificacionPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIdentificacionPlantaActionPerformed
        
        KNumeroIdentificacionPlanta11D identificacion = new KNumeroIdentificacionPlanta11D();
        identificacion.setVisible(true);
        identificacion.setResizable(false);
        identificacion.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_botonIdentificacionPlantaActionPerformed

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        
        DCierreSesion cerrar = new DCierreSesion();
        cerrar.setVisible(true);
        cerrar.setResizable(false);
        cerrar.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_botonCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DConfiguracion4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DConfiguracion4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DConfiguracion4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DConfiguracion4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DConfiguracion4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonBorrarCuenta;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonID;
    private javax.swing.JButton botonIdentificacionPlanta;
    private javax.swing.JButton botonModificarContra;
    private javax.swing.JButton botonModificarDatos;
    private javax.swing.JLabel jLabel1;
    private java.awt.Panel panel3;
    // End of variables declaration//GEN-END:variables
}
