/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author elian
 */
public class KAlmacenamientoPlantas11 extends javax.swing.JFrame {

    /**
     * Creates new form AlmacenamientoPlantas11
     */
    public KAlmacenamientoPlantas11() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(57,143,136));
        setIconImage(getIconImage());
    }
    
    @Override
    public final Image getIconImage(){
    
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/icon.png"));
        return retValue;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        botonHome = new javax.swing.JButton();
        botonBusqueda = new javax.swing.JButton();
        botonEnfermedades = new javax.swing.JButton();
        botonAlmacenamiento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonRegistro = new javax.swing.JButton();
        botonLogin = new javax.swing.JButton();
        panel2 = new java.awt.Panel();
        botonAgregar = new javax.swing.JButton();
        botonMisPlantas = new javax.swing.JButton();
        botonIdentificacion = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setForeground(new java.awt.Color(255, 255, 255));
        panel1.setName(""); // NOI18N
        panel1.setPreferredSize(new java.awt.Dimension(401, 42));

        botonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonHome1.png"))); // NOI18N
        botonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHomeActionPerformed(evt);
            }
        });

        botonBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonBuscarPlantas.png"))); // NOI18N
        botonBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBusquedaActionPerformed(evt);
            }
        });

        botonEnfermedades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonBuscarEnfermedades.png"))); // NOI18N
        botonEnfermedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnfermedadesActionPerformed(evt);
            }
        });

        botonAlmacenamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonAlmacenamiento1.png"))); // NOI18N
        botonAlmacenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAlmacenamientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(botonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(botonBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(botonEnfermedades, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(botonAlmacenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAlmacenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEnfermedades, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBusqueda)
                    .addComponent(botonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Mi jardin");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Agregar Planta");

        botonRegistro.setBackground(new java.awt.Color(57, 143, 136));
        botonRegistro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonRegistro.setText("Registrarme");
        botonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistroActionPerformed(evt);
            }
        });

        botonLogin.setBackground(new java.awt.Color(57, 143, 136));
        botonLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonLogin.setText("Iniciar Sesion");
        botonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLoginActionPerformed(evt);
            }
        });

        panel2.setBackground(new java.awt.Color(0, 0, 0));
        panel2.setPreferredSize(new java.awt.Dimension(50, 2));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        botonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonAgregar.png"))); // NOI18N
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        botonMisPlantas.setBackground(new java.awt.Color(57, 143, 136));
        botonMisPlantas.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        botonMisPlantas.setText("º Mis plantas");
        botonMisPlantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMisPlantasActionPerformed(evt);
            }
        });

        botonIdentificacion.setBackground(new java.awt.Color(57, 143, 136));
        botonIdentificacion.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        botonIdentificacion.setText("° Numero de identificacion de planta");
        botonIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIdentificacionActionPerformed(evt);
            }
        });

        botonEliminar.setBackground(new java.awt.Color(57, 143, 136));
        botonEliminar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        botonEliminar.setText("° Extraccion de Planta de Mi Jardin");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
            .addComponent(panel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonIdentificacion)
                            .addComponent(botonMisPlantas)
                            .addComponent(botonEliminar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(botonRegistro)
                        .addGap(9, 9, 9)
                        .addComponent(botonLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)))
                .addGap(27, 27, 27)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(61, 61, 61)
                .addComponent(botonMisPlantas)
                .addGap(27, 27, 27)
                .addComponent(botonIdentificacion)
                .addGap(31, 31, 31)
                .addComponent(botonEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEnfermedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnfermedadesActionPerformed
        
        JBusquedaEnfermedades10 enfermedades = new JBusquedaEnfermedades10();
        enfermedades.setVisible(true);
        enfermedades.setResizable(false);
        enfermedades.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_botonEnfermedadesActionPerformed

    private void botonBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBusquedaActionPerformed
        
        IBusquedaPlantas9 busqueda = new IBusquedaPlantas9();
        busqueda.setVisible(true);
        busqueda.setResizable(false);
        busqueda.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_botonBusquedaActionPerformed

    private void botonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHomeActionPerformed
        
        CPrincipal3A principal = new CPrincipal3A();
        principal.setVisible(true);
        principal.setResizable(false);
        principal.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_botonHomeActionPerformed

    private void botonAlmacenamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAlmacenamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAlmacenamientoActionPerformed

    private void botonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistroActionPerformed
        
        BRegistro2D registro = new BRegistro2D();        
        registro.setVisible(true);
        registro.setResizable(false);
        registro.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_botonRegistroActionPerformed

    private void botonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLoginActionPerformed
        
        ALogin1 login = new ALogin1();
        login.setVisible(true);
        login.setResizable(false);
        login.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_botonLoginActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        
        KKAgregacionPlanta11F agregacion = new KKAgregacionPlanta11F();
        agregacion.setVisible(true);
        agregacion.setResizable(false);
        agregacion.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonMisPlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMisPlantasActionPerformed
        
        KMisPlantas11G misPlantas = new KMisPlantas11G();
        misPlantas.setVisible(true);
        misPlantas.setResizable(false);
        misPlantas.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_botonMisPlantasActionPerformed

    private void botonIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIdentificacionActionPerformed
        
        KNumeroIdentificacionPlanta11H identificacion = new KNumeroIdentificacionPlanta11H();
        identificacion.setVisible(true);
        identificacion.setResizable(false);
        identificacion.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_botonIdentificacionActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        
        KEliminacionPlantaMiJardin11I eliminacion = new KEliminacionPlantaMiJardin11I();
        eliminacion.setVisible(true);
        eliminacion.setResizable(false);
        eliminacion.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_botonEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KAlmacenamientoPlantas11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KAlmacenamientoPlantas11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KAlmacenamientoPlantas11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KAlmacenamientoPlantas11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KAlmacenamientoPlantas11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonAlmacenamiento;
    private javax.swing.JButton botonBusqueda;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonEnfermedades;
    private javax.swing.JButton botonHome;
    private javax.swing.JButton botonIdentificacion;
    private javax.swing.JButton botonLogin;
    private javax.swing.JButton botonMisPlantas;
    private javax.swing.JButton botonRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    // End of variables declaration//GEN-END:variables
}
