/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.sql.*;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author elian
 */
public class KKAgregacionPlanta11B extends javax.swing.JFrame {

    /**
     * Creates new form BusquedaAlmacenar
     */
    public KKAgregacionPlanta11B() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(57,143,136));
        setIconImage(getIconImage());
    }
    
    @Override
    public final Image getIconImage(){
        
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/icon.png"));
        return retValue;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        botonAtras = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        botonCatus = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        botonHelecho = new javax.swing.JButton();
        botonSuculenta = new javax.swing.JButton();
        botonCroto = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonAtras.png"))); // NOI18N
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Mi planta");

        panel2.setBackground(new java.awt.Color(0, 0, 0));
        panel2.setPreferredSize(new java.awt.Dimension(50, 2));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 811, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Seleccione el tipo de especie:");

        txtNombre.setBackground(new java.awt.Color(204, 204, 204));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        botonCatus.setBackground(new java.awt.Color(57, 143, 136));
        botonCatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonCatus.setText("Cactus");
        botonCatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCatusActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Descripcion (Opcional. Maximo 30 palabras)");

        txtDescripcion.setBackground(new java.awt.Color(204, 204, 204));

        botonHelecho.setBackground(new java.awt.Color(57, 143, 136));
        botonHelecho.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonHelecho.setText("Helecho");
        botonHelecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHelechoActionPerformed(evt);
            }
        });

        botonSuculenta.setBackground(new java.awt.Color(57, 143, 136));
        botonSuculenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonSuculenta.setText("Suculenta");
        botonSuculenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSuculentaActionPerformed(evt);
            }
        });

        botonCroto.setBackground(new java.awt.Color(57, 143, 136));
        botonCroto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonCroto.setText("Croto");
        botonCroto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(botonCatus)
                                .addGap(71, 71, 71)
                                .addComponent(botonHelecho)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botonSuculenta)
                                .addGap(36, 36, 36)
                                .addComponent(botonCroto)
                                .addGap(83, 83, 83))))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCatus)
                    .addComponent(botonHelecho, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSuculenta)
                    .addComponent(botonCroto))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(88, 88, 88)
                    .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(332, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        
        KAlmacenamientoPlantas11A almacenamiento = new KAlmacenamientoPlantas11A();
        almacenamiento.setVisible(true);
        almacenamiento.setResizable(false);
        almacenamiento.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonCatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCatusActionPerformed
        
        try{
        
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/gss_prueba2", "root", "");
            PreparedStatement pst = cn.prepareStatement("insert into plantas values(?,?,?,?)");
            pst.setString(1, "0");
            pst.setString(2, txtNombre.getText().trim());
            pst.setString(3, txtDescripcion.getText().trim());
            pst.setString(4, "Cactus");
            
             if(txtNombre.getText().length()==0){
                
                JOptionPane.showMessageDialog(null, "Por favor, ingresar el nombre de la planta");
            
            }else{
                
                pst.executeUpdate();
                txtNombre.setText("");
                txtDescripcion.setText("");
                JOptionPane.showMessageDialog(null, "La planta se almaceno correctamente");
                this.dispose();
                KAlmacenamientoPlantas11A almacenamiento = new KAlmacenamientoPlantas11A();
                almacenamiento.setVisible(true);
                almacenamiento.setResizable(false);
                almacenamiento.setLocationRelativeTo(null);
            
            }
        
        }catch(Exception e){}
        
    }//GEN-LAST:event_botonCatusActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void botonHelechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHelechoActionPerformed
        
        try{
            
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/gss_prueba2", "root", "");
            PreparedStatement pst = cn.prepareStatement("insert into plantas values(?,?,?,?)");
            pst.setString(1, "0");
            pst.setString(2,txtNombre.getText().trim());
            pst.setString(3,txtDescripcion.getText().trim());
            pst.setString(4,"Helecho");
            
            if(txtNombre.getText().length()==0){
                
                JOptionPane.showMessageDialog(null, "Por favor, ingresar todos los campos requridos");
            
            }else{
                
                pst.executeUpdate();
                txtNombre.setText("");
                txtDescripcion.setText("");
                JOptionPane.showMessageDialog(null, "La planta se almaceno correctamente");
                this.dispose();
                KAlmacenamientoPlantas11A almacenamiento = new KAlmacenamientoPlantas11A();
                almacenamiento.setVisible(true);
                almacenamiento.setResizable(false);
                almacenamiento.setLocationRelativeTo(null);
            
            }
        
        }catch(Exception e){}
        
    }//GEN-LAST:event_botonHelechoActionPerformed

    private void botonSuculentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSuculentaActionPerformed
        
        try{
            
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/gss_prueba2", "root", "");
            PreparedStatement pst = cn.prepareStatement("insert into plantas values(?,?,?,?)");
            pst.setString(1,"0");
            pst.setString(2, txtNombre.getText().trim());
            pst.setString(3,txtDescripcion.getText().trim());
            pst.setString(4,"Suculenta");
            
            if(txtNombre.getText().length()==0){
                
                JOptionPane.showMessageDialog(null, "Por favor, ingresar todos los campos requridos");
            
            }else{
                
                pst.executeUpdate();
                txtNombre.setText("");
                txtDescripcion.setText("");
                JOptionPane.showMessageDialog(null, "La planta se almaceno correctamente");
                this.dispose();
                KAlmacenamientoPlantas11A almacenamiento = new KAlmacenamientoPlantas11A();
                almacenamiento.setVisible(true);
                almacenamiento.setResizable(false);
                almacenamiento.setLocationRelativeTo(null);
            
            }
        
        }catch(Exception e){}
        
    }//GEN-LAST:event_botonSuculentaActionPerformed

    private void botonCrotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrotoActionPerformed
        
        try{
            
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/gss_prueba2", "root", "");
            PreparedStatement pst = cn.prepareStatement("insert into plantas values(?,?,?,?)");
            pst.setString(1, "0");
            pst.setString(2, txtNombre.getText().trim());
            pst.setString(3,txtDescripcion.getText().trim());
            pst.setString(4,"Croto");
            
            if(txtNombre.getText().length()==0){
                
                JOptionPane.showMessageDialog(null, "Por favor, ingresar todos los campos requridos");
            
            }else{
                
                pst.executeUpdate();
                txtNombre.setText("");
                txtDescripcion.setText("");
                JOptionPane.showMessageDialog(null, "La planta se almaceno correctamente");
                this.dispose();
                KAlmacenamientoPlantas11A almacenamiento = new KAlmacenamientoPlantas11A();
                almacenamiento.setVisible(true);
                almacenamiento.setResizable(false);
                almacenamiento.setLocationRelativeTo(null);
            
            }
        
        }catch(Exception e){}
        
    }//GEN-LAST:event_botonCrotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KKAgregacionPlanta11B.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KKAgregacionPlanta11B.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KKAgregacionPlanta11B.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KKAgregacionPlanta11B.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KKAgregacionPlanta11B().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonCatus;
    private javax.swing.JButton botonCroto;
    private javax.swing.JButton botonHelecho;
    private javax.swing.JButton botonSuculenta;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private java.awt.Panel panel2;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
